language: c
before_install: sudo apt-get update
install: sudo apt-get install check
script: ./configure && make && make -s check
compiler:
  - clang
  - gcc
branches:
  only:
    - dev
notifications:
  email:
    - joebew42@gmail.com
    - enzodicicco@gmail.com