language: c
before_install: sudo apt-get update
install: sudo apt-get install dh-autoreconf
script: ./script/build travis
compiler:
  - clang
  - gcc
branches:
  only:
    - dev
notifications:
  email:
    - joebew42@gmail.com
    - enzodicicco@gmail.com